name: Test the run-oci-cli-command action

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-running-instances:
    runs-on: ubuntu-latest
    name: Use the run-oci-cli-command to retrieve a list of running instances
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve the OCID of a named compartment in tenancy
        uses: ./
        id: region
        with:
          command: 'iam region list --raw-ouput'
          query: "data[0].name"
          silent: false

      - name: Test1
        run: echo "[ ${{ steps.region.outputs.raw_output }} ]"

      - name: Test2
        run: echo "[ ${{ steps.region.outputs.output }} ]"
